version: '2'

# Define the services/containers to be run
services:
  node-server: # name of service
    build: . # specify directory of the Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"
